name: ProgressBarDemo
main: io.github.secondflight.ProgressBar.MainPlugin
version: 1
description: >
                 Progress Bar Demo
commands:
  progressbar:
    description: Type /pb for info.
  pb:
    description: Type /pb for info.